version: '3.8'

services:
  django:
    image: python:3.10-slim
    container_name: django_server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs are output in real-time
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

