version: '3.8'

services:
  django:
    image: python:3.10-slim
    container_name: django_server
    working_dir: /app
    volumes:
      - .:/app
      - ../resources/challenge_c/3_OpenDroneMap:/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs are output in real-time
    secrets:
      - django_env
    command: > #   python test.py
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python app/test.py
      "

secrets:
  django_env:
    file: .env